Patch device
grupadotnet/Aqua-Sharp-Backend pull request #31
Opened 2023-05-24 22:49 UTC by Nieznany4321

~update device with custom number of parameters

2023-05-28 14:31 UTC, SzczepanWikar commented on Models/ViewModels/Aquarium/EditAquariumViewModel.cs
> +        public TimeOnly Dawn { get; set; }
Każda właściwość powinna być opcjonalna

2023-05-28 22:07 UTC, Nieznany4321 commented on Models/ViewModels/Aquarium/EditAquariumViewModel.cs
> +        public TimeOnly Dawn { get; set; }
Zmieniony sposób reakcji metody Update: 
- zmiennia tylko wartości określone w EditAquariumViewModel,
- zmiennia dowolną ilość przekazanych wartości w jsonBody
Dodany Automapper <EditAquariumViewModel, Aquarium>

MeasurementFrequency:
![image](https://github.com/grupadotnet/Aqua-Sharp-Backend/assets/59314982/22e6396a-6e5b-49f0-951d-50d0fa3e37f0)
wszystkie wymagane property zmienione:
![image](https://github.com/grupadotnet/Aqua-Sharp-Backend/assets/59314982/1cdc7366-04f8-4fcf-bd0f-19110605f0ab)

Wyjątek przy zmianie property poza klasą EditAquariumViewModel:
![image](https://github.com/grupadotnet/Aqua-Sharp-Backend/assets/59314982/adb4ad5e-3ea5-426d-8f0a-47f98ead7aa6)

2023-05-29 17:55 UTC, SzczepanWikar requested changes

2023-05-29 17:55 UTC, SzczepanWikar commented on Models/ViewModels/Aquarium/EditAquariumViewModel.cs
> +        public TimeOnly Dawn { get; set; }
Powinien być 400 Bad Request, a nie 500

2023-05-30 19:56 UTC, Nieznany4321 commented on Models/ViewModels/Aquarium/EditAquariumViewModel.cs
> +        public TimeOnly Dawn { get; set; }
Dodano obsługe próby zmiany niepoprawnej warości:
![image](https://github.com/grupadotnet/Aqua-Sharp-Backend/assets/59314982/9e38ef75-6fda-4e71-88d9-9aac77106e64)

2023-05-30 20:04 UTC, Nieznany4321 commented on Models/ViewModels/Aquarium/EditAquariumViewModel.cs
> +        public TimeOnly Dawn { get; set; }
![image](https://github.com/grupadotnet/Aqua-Sharp-Backend/assets/59314982/f401694e-b855-4d53-8978-d5994e2a2e60)

2023-05-30 20:27 UTC, SzczepanWikar approved these changes

2023-05-30 20:27 UTC, merged